### PR TITLE
Add demo

### PR DESCRIPTION
**Pull request by Zyst**
Added a demo, very lightly styled the markdown file, and added a description.

### CODE REVIEW

**Comment by Zyst** [comment]
Ah, I just saw the GHPages at the top, feel free to disregard this PR. Although you should put that in the readme regardless.

Cheers.

**Comment by chantastic** [comment]
@Zyst thanks for the PR! sorry it took me so long to respond. apparently i wasn't subscribed 😬

Thanks for putting this together!

**Comment by Zyst** [comment]
Cool! Great readme now, thanks for updating it!

**Comment by chantastic** [comment]
@Zyst thanks for motivating me to  do it! it'd had been a while since i paid much attention to this :)

**Pull request merged**
